language: go
go: "1.10"

env:
  - DEP_VERSION="0.4.1"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep
  # Make test data generator executable
  - chmod +x generate_test_data.sh

install:
  - dep ensure
  - ./generate_test_data
